import { readFileSync, writeFileSync } from "node:fs";
const path = "client/src/pages/Home.tsx";
let source = readFileSync(path, "utf8");
const old = '  const searchResults = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return []; const all = [...state.goals.map((x) => ({ type: "Goal", id: x.id, title: x.title, text: x.description })), ...state.projects.map((x) => ({ type: "Project", id: x.id, title: x.name, text: x.description })), ...state.tasks.map((x) => ({ type: "Task", id: x.id, title: x.title, text: x.description || "" })), ...state.journal.map((x) => ({ type: "Journal", id: x.id, title: x.title, text: x.body }))]; return all.filter((x) => `${x.title} ${x.text}`.toLowerCase().includes(q)).slice(0, 12); }, [query, state]);';
const next = '  const searchResults = useMemo(() => { if (!state) return []; const q = query.trim().toLowerCase(); if (!q) return []; const all = [...state.goals.map((x) => ({ type: "Goal", id: x.id, title: x.title, text: x.description })), ...state.projects.map((x) => ({ type: "Project", id: x.id, title: x.name, text: x.description })), ...state.tasks.map((x) => ({ type: "Task", id: x.id, title: x.title, text: x.description || "" })), ...state.journal.map((x) => ({ type: "Journal", id: x.id, title: x.title, text: x.body }))]; return all.filter((x) => `${x.title} ${x.text}`.toLowerCase().includes(q)).slice(0, 12); }, [query, state]);';
if (!source.includes(old)) throw new Error("searchResults block not found");
source = source.replace(old, next);
source = source.replace('  if (!state) return <div className="boot-screen"><Loader size={30} /><p>Resolving your local workspace…</p></div>;\n  const stats', '  const stats');
source = source.replace('  const stats = calculateProgress(state);', '  if (!state) return <div className="boot-screen"><Loader size={30} /><p>Resolving your local workspace…</p></div>;\n  const stats = calculateProgress(state);');
writeFileSync(path, source);
